config/routes.rb
Rails.application.routes.draw do
  # resources :surveys
  resources :encounters
  resources :responses
  resources :questions, only: :show

	get '/', to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	layout 'dashboard'

	def index
		@encounters = Encounter.all
		@survey = Survey.first
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">  

  <main>

    <div class="row">
      <div class="col s12">
        <div class="card-panel white" id="#af-table">
          <div class="left">
            <h4>Today, 04/09/2018 <span class="gray">UNIT 4S</span></h4>
          </div>          
          <div class="right">
            <a class="waves-effect waves-light btn"><i class="material-icons left">edit</i>Edit</a>
            <a class="waves-effect waves-light btn" href="<%= new_encounter_path %>"><i class="material-icons left">add</i>New Bed</a>
          </div>
          <table>
            <thead>
              <tr>
                  <th></th>
                  <th>Assigned Bed</th>
                  <th>Patient Name</th>
                  <th>Attending Physician</th>
                  <th>A <span>Pain</span></th>
                  <th>B <span>SAT</span></th>
                  <th>C <span>Benzo</span></th>
                  <th>D <span>Delerium</span></th>
                  <th>E <span>Mobility</span></th>
                  <th>F <span>Family</span></th>
              </tr>
            </thead>

            <tbody>
              
              <% @encounters.each_with_index do |encounter,i| %>

              <tr>
                <td></td>
                <td><a href="<%= edit_encounter_path(encounter) %>">A<%= i + 1 %></a></td>
                <td><%= encounter.subject_name %></td>
                <td><%= encounter.physician %></td>
                
                <% Survey::SECTIONS.each do |section_name| %>

                  <% status = Response.section_status(section_name,encounter,@survey.id); puts "section #{section_name} #{status}" ; %>

                  <% case status
                    when 0 %> <!-- Not Started -->
                    <td><i class="material-icons red">cancel</i></td>
                  <% when 1 %> <!-- Incomplete -->
                    <td><i class="material-icons yellow">do_not_disturb_on</i></td>
                  <% when 2 %> <!-- Complete -->
                    <td><i class="material-icons green">check</i></td>
                  <% end %>

                <% end %>
              </tr>

              <% end %>

            </tbody>
          </table>


          <p><small><span class="gray">Last updated: <%= DateTime.now.strftime("%b %e, %Y %H:%M") %></span></small></p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col s3">
        <div class="card-panel white" id="#total-compliance">
          <h4>Today</h4>
          <h4 style="text-align:center;color:#FDD200">60%</h4>
        </div>
      </div>  

      <div class="col s9">
        <div class="card-panel white" id="#weeks-compliance">
          <h4>This Week <span class="gray" id="this-week-label">(<%= (Time.now - 5.days).strftime('%m/%e') %> - <%= Time.now.strftime('%m/%e') %>)</span></h4>
          <div id="compliance-trend-container"></div>
        </div>
      </div>  

    </div>    


  </main>

  <footer>
  </footer>

</div><!-- end container -->