config/routes.rb
Rails.application.routes.draw do
  # resources :surveys
  resources :encounters
  resources :responses
  resources :questions, only: :show

	get '/', to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/encounter.rb
class Encounter < ApplicationRecord

	has_many :responses

	before_create :generate_mrn

	def get_response(question_id)
		responses = self.responses.where("question_id = #{question_id}")
		if responses.empty?
			# create a response and return it if question exists
			if Question.find(question_id)
				Response.create(encounter_id: self.id, question_id: question_id)
			else
				nil
			end
		else
			# return first response that matches with question id
			responses.first
		end
	end

	def generate_mrn 
		self.mrn = (rand*1000000).to_i
	end

end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.all
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
    @survey = Survey.last
    @responses = @encounter.responses.group_by{|r| r.question.section_name}

    respond_to do |format|
      format.html
      format.json { render :show, status: :ok, location: @encounter }
    end      
  end

  # GET /encounters/new
  def new
    @encounter = Encounter.new
    @survey = Survey.last
    # redirect_to edit_encounter_path(@encounter.id)
  end

  # GET /encounters/1/edit
  def edit
    @survey = Survey.last
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to edit_encounter_path(@encounter) }
        format.json { render :show, status: :created, location: @encounter }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
    respond_to do |format|
      if @encounter.update(encounter_params)
        format.html { redirect_to @encounter, notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @encounter }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to encounters_url, notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:subject_name,:physician, :bed)
    end
end

app/helpers/encounter_helper.rb
module EncounterHelper

	def returnSectionStatus(section_name,encounter,survey_id)
		status = Response.section_status(section_name,encounter,survey_id)
		case status
		when 0
			return {:icon => '<i class="material-icons red">cancel</i>',
					:status_name => "Not Started"}
		when 1
			return {:icon => '<i class="material-icons yellow">do_not_disturb_on</i>',
					:status_name => "Incomplete"}
		when 2
			return {:icon => '<i class="material-icons green">check</i>',
					:status_name => "Complete"}
		end

	end

end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/views/encounters/_section.html.erb
  <%  
    questions.each do |question| 
      # find response for this question and encounter
      response = encounter.get_response(question.id)
  %>

  <%= form_for response, remote: true, html: {class: "response"} do |resp| %>

    <!-- Survey Question -->
    <div class="question">

      <div class="question-text">
        <%= question.title %>. <%= question.body %>
      </div>

      <!-- Survey Options -->
      <div class="answers">
        <%
          options = question.options
          options.each do |option|
        %>  

          <% if option.kind == "multiple_choice" %>
          <!-- Multiple Choice -->          
            <p>
              <label>
                <%= radio_button_tag('response[body]', option.body, (response.body == option.body)) %>
                <span><%= option.body %></span>
              </label>
            </p>

          <% elsif option.kind == "free_text" %>
          <!-- Free Text -->

            <%= resp.text_field :body %>

          <% end  # end if option.kind %>

        <% end # end options.each %>

      </div><!-- end .answers -->

    </div><!-- end .question -->

  <% end # end form_for response %>

  <% end # end questions.each %>

app/views/encounters/edit.html.erb
<div class="row">
  <div class="col s12"> 

    <!-- Main screen structure -->
    <header>
      <div class="nav">
            <a href="<%= encounter_path(@encounter) %>"><i class="material-icons">menu</i></a>
      </div>
      <div id="patient-meta">
        <div id="encounter-id" style="display:none;"><%= @encounter.id %></div>
        <h1><%= @encounter.subject_name %></h1>
        <p>Attending Physician: <%= @encounter.physician %></p>
        <p>Admitted: <%= (@encounter.created_at - 2.days).strftime("%m/%d/%y") %></p>
        <p>Bed: <%= @encounter.bed %></p>
        <p>MRN: <%= @encounter.mrn %></p>
      </div>

    </header>

  </div>
</div>

<div class="row">

  <div class="col s12">

    <main>
      <div id="af-nav">

        <ul class="collapsible">
          <%  sections = [{title: "A-Pain",name:"A"},
                          {title: "B-SAT",name:"B"},
                          {title: "C-Benzo",name:"C"},
                          {title: "D-Delirium",name:"D"},
                          {title: "E-Mobility",name:"E"}]

              sections.each_with_index do |section,index| %>

            <% statusHash = returnSectionStatus(section[:name],@encounter,@survey.id) %>

            <!-- Survey Section -->
            <li data-section-name="<%= section[:name] %>">
              <div class="collapsible-header measure-row <%= index == 0 ? 'first' : '' %> <%= index == (sections.length-1) ? 'last' : '' %>">
                <span class="status-icon"><%= statusHash[:icon].html_safe %></span>
                <div class="measure-row-content">
                  <div class="left">
                    <div class="top"><strong><%= section[:title] %></strong></div>
                    <div class="bottom status-name"><%= statusHash[:status_name] %></div>
                  </div>
                  <div class="right">
                    <i class="material-icons">keyboard_arrow_right</i>
                  </div>
                </div>
              </div>
              <div class="collapsible-body">

                <% questions = @survey.questions.where("section_name = '#{section[:name]}'") %>
                <%= render partial: 'section', :locals => {:questions => questions, :encounter => @encounter} %>
                
              </div>
            </li>      

          <% end  # end sections.each %>            
          
        </ul>

      </div>
            
    </main>
  
  </div>
</div>

<script>
  $('.collapsible').collapsible();
  $('.modal').modal({});
  $('.modal').modal("open");
</script>

app/views/encounters/index.html.erb
<div class="row">

  <div class="col s12">

<!-- Main screen structure -->
    <header>
      <div class="nav">
        <a href="<%= new_encounter_path %>"><i class="material-icons">menu</i></a>
      </div>

      <div id="patient-meta">
        <h1>Encounters <span><a class="btn-floating btn-large waves-effect waves-light" href="<%= new_encounter_path %>"><i class="material-icons">add</i></a></span></h1>
         
      </div>

    </header>

  </div>

</div> <!-- end row -->

<div class="row">

  <div class="col s12">

    <main>

      <div id="af-nav">

        <ul class="collection">

          <% @encounters.each do |encounter| %>

          <li>
            <a href="<%= edit_encounter_path(encounter) %>">
            <div class="collection-item measure-row first">

              <div class="row measure-row-content">

                <div class="col s3 measure-name">
                  <%= encounter.id %>
                </div>

              </div>

            </div>
            </a>
          </li>

          <% end %>
          
        </ul>

      </div>
            
    </main>

  </div>

</div><!-- end row -->

app/views/encounters/new.html.erb
<%= form_for @encounter do |f| %>
<div class="row">
	<div class="input-field col s12">
		<%= f.text_field :subject_name %>
		<%= label :encounter, :subject_name %>
	</div>
	<div class="input-field col s12">
		<%= f.text_field :physician %>
		<%= label :encounter, :physician %>
	</div>
	<div class="input-field col s12">
		<%= f.text_field :bed %>
		<%= label :encounter, :bed %>
	</div>
	<div class="input-field col s12">
		<button class="btn waves-effect waves-light" type="submit" name="action">Submit
			<i class="material-icons right">send</i>
		</button>
	</div>
</div>

<% end %>

app/views/encounters/show.html.erb
<div class="row">

  <div class="col s12">

<!-- Main screen structure -->
    <header>
      <div class="nav">
        <a href="<%= edit_encounter_path(@encounter) %>"><i class="material-icons">menu</i></a>
      </div>

      <div id="patient-meta">
        <h1><%= @encounter.subject_name %></h1>
        <p>Attending Physician: <%= @encounter.physician %></p>
        <p>Admitted: <%= (@encounter.created_at - 2.days).strftime("%m/%d/%y") %></p>
        <p>Bed: <%= @encounter.bed %></p>
        <p>MRN: <%= @encounter.mrn %></p>
      </div>

    </header>

  </div>

</div> <!-- end row -->

<div class="row">

  <div class="col s12">

    <main>

      <div id="af-nav">

        <ul class="collection">

          <!-- Survey section -->
          <li>
            <div class="collection-item measure-row first">

              <div class="row measure-row-content">

                <% statusHash = returnSectionStatus("A",@encounter,@survey.id) %>

                <div class="col s3 measure-name">
                    <%= statusHash[:icon].html_safe %>
                    <div class="title">A-Pain</div>
                    <div class="completion"><%= statusHash[:status_name] %></div>
                </div>
                <div class="col s9">
                  <ul>
                    <%  responses = @responses["A"] || []
                        responses.sort_by{|a| a.question.order}.each do |resp| %>
                    <li>
                      <%= resp.question.answer_display %> <span class="answerbody"><%= resp.body %></span> <a href="#" class="response-trend" data-question-id="<%=resp.question_id %>"><i class="opentrend material-icons">open_in_new</i></a>
                    </li>
                    <% end %>
                  </ul>
                </div>

              </div>

            </div>
          </li>

          <!-- Survey section -->
          <li>
            <div class="collection-item measure-row ">

              <div class="row measure-row-content">

                <% statusHash = returnSectionStatus("B",@encounter,@survey.id) %>

                <div class="col s3 measure-name">
                    <%= statusHash[:icon].html_safe %>
                    <div class="title">B-SAT</div>
                    <div class="completion"><%= statusHash[:status_name] %></div>
                </div>
                <div class="col s9">
                  <ul>
                    <%  responses = @responses["B"] || []
                        responses.sort_by{|a| a.question.order}.each do |resp| %>
                    <li>
                      <%= resp.question.answer_display %> <span class="answerbody"><%= resp.body %></span> <a href="#" class="response-trend" data-question-id="<%=resp.question_id %>"><i class="opentrend material-icons">open_in_new</i></a>
                    </li>
                    <% end %>
                  </ul>
                </div>

              </div>

            </div>
          </li>

          <!-- Survey section -->
          <li>
            <div class="collection-item measure-row ">

              <div class="row measure-row-content">

                <% statusHash = returnSectionStatus("C",@encounter,@survey.id) %>

                <div class="col s3 measure-name">
                    <%= statusHash[:icon].html_safe %>
                    <div class="title">C-Benzo</div>
                    <div class="completion"><%= statusHash[:status_name] %></div>
                </div>
                <div class="col s9">
                  <ul>
                    <%  responses = @responses["C"] || []
                        responses.sort_by{|a| a.question.order}.each do |resp| %>
                    <li>
                      <%= resp.question.answer_display %> <span class="answerbody"><%= resp.body %></span> <a href="#" class="response-trend" data-question-id="<%=resp.question_id %>"><i class="opentrend material-icons">open_in_new</i></a>
                    </li>
                    <% end %>
                  </ul>
                </div>

              </div>

            </div>
          </li>

          <!-- Survey section -->
          <li>
            <div class="collection-item measure-row ">

              <div class="row measure-row-content">

                <% statusHash = returnSectionStatus("D",@encounter,@survey.id) %>

                <div class="col s3 measure-name">
                    <%= statusHash[:icon].html_safe %>
                    <div class="title">D-Delirium</div>
                    <div class="completion"><%= statusHash[:status_name] %></div>
                </div>
                <div class="col s9">
                  <ul>
                    <%  responses = @responses["D"] || []
                        responses.sort_by{|a| a.question.order}.each do |resp| %>
                    <li>
                      <%= resp.question.answer_display %> <span class="answerbody"><%= resp.body %></span> <a href="#" class="response-trend" data-question-id="<%=resp.question_id %>"><i class="opentrend material-icons">open_in_new</i></a>
                    </li>
                    <% end %>
                  </ul>
                </div>

              </div>

            </div>
          </li>  

          <!-- Survey section -->
          <li>
            <div class="collection-item measure-row last">

              <div class="row measure-row-content">

                <% statusHash = returnSectionStatus("E",@encounter,@survey.id) %>

                <div class="col s3 measure-name">
                    <%= statusHash[:icon].html_safe %>
                    <div class="title">E-Mobility</div>
                    <div class="completion"><%= statusHash[:status_name] %></div>
                </div>
                <div class="col s9">
                  <ul>
                    <%  responses = @responses["E"] || []
                        responses.sort_by{|a| a.question.order}.each do |resp| %>
                    <li>
                      <%= resp.question.answer_display %> <span class="answerbody"><%= resp.body %></span> <a href="#" class="response-trend" data-question-id="<%=resp.question_id %>"><i class="opentrend material-icons">open_in_new</i></a>
                    </li>
                    <% end %>
                  </ul>
                </div>

              </div>

            </div>
          </li>                                                  


        </ul>

      </div>
            
    </main>

  </div>

</div><!-- end row -->